// <auto-generated />
using System;
using BookingTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingTrackerDbContext))]
    [Migration("20260806104951_AddAvailabilityOverrides")]
    partial class AddAvailabilityOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingTracker.Domain.Entities.AvailabilityException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId", "Date", "EndDate");

                    b.ToTable("AvailabilityExceptions", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.AvailabilityOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId", "Date")
                        .IsUnique();

                    b.ToTable("AvailabilityOverrides", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BufferAfterMinutes")
                        .HasColumnType("int");

                    b.Property<int>("BufferBeforeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxBookingWindowDays")
                        .HasColumnType("int");

                    b.Property<int?>("MaxBookingsPerDay")
                        .HasColumnType("int");

                    b.Property<byte>("MeetingProvider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("MinNoticeMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BookingPages", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmailNotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MeetingStartsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinutesBeforeEvent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("QueuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BookingPageId");

                    b.HasIndex("EmailNotificationId");

                    b.HasIndex("BookingSessionId", "MinutesBeforeEvent")
                        .IsUnique()
                        .HasDatabaseName("UX_BookingReminders_Session_Offset_Scheduled")
                        .HasFilter("[Status] = 0");

                    b.HasIndex("Status", "ScheduledForUtc");

                    b.ToTable("BookingReminders", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AbandonedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BookingPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("CancelledBy")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastClientSequenceNumber")
                        .HasColumnType("int");

                    b.Property<byte?>("MeetingProvider")
                        .HasColumnType("tinyint");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PublicToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RescheduleCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RescheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("SelectedDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("SelectedTime")
                        .HasColumnType("time");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique()
                        .HasFilter("[BookingReference] IS NOT NULL");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasFilter("[PublicToken] IS NOT NULL");

                    b.HasIndex("BookingPageId", "Status");

                    b.HasIndex("Status", "LastActivityAt");

                    b.HasIndex("Status", "SelectedDate", "SelectedTime");

                    b.ToTable("BookingSessions", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSessionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BookingPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientSequenceNumber")
                        .HasColumnType("int");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint");

                    b.Property<string>("FieldName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingPageId", "Timestamp");

                    b.HasIndex("SessionId", "ClientSequenceNumber");

                    b.ToTable("BookingSessionEvents", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.CalendarConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AccessTokenExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AutoDeleteCancelledBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AutoUpdateRescheduledBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultReminderMinutes")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EventTitleFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("{Service Name} with {Guest Name}");

                    b.Property<string>("EventVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("default");

                    b.Property<bool>("ExportBookings")
                        .HasColumnType("bit");

                    b.Property<string>("ExternalAccountEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalCalendarId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalCalendarName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ImportBusyEvents")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFailedSyncAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastSyncedAtUtc");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Provider")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId")
                        .IsUnique();

                    b.ToTable("CalendarConnections", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.CalendarSyncedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingSessionId")
                        .IsUnique();

                    b.HasIndex("CalendarConnectionId");

                    b.ToTable("CalendarSyncedEvents", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.EmailNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("BookingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventLogFieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcsContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcsFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IcsMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BookingSessionId");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("EmailNotifications", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotifyGuestOnBooking")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOrganizerOnBooking")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOrganizerOnReminderSent")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReminderMinutesBeforeEventCsv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RemindersEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId")
                        .IsUnique();

                    b.ToTable("NotificationSettings", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizers", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("OrganizerId", "ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("WorkingScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkingScheduleId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkingDays", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId")
                        .IsUnique();

                    b.ToTable("WorkingSchedules", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.AvailabilityException", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.AvailabilityOverride", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("BookingTracker.Domain.ValueObjects.TimeRange", "Ranges", b1 =>
                        {
                            b1.Property<Guid>("AvailabilityOverrideId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time");

                            b1.HasKey("AvailabilityOverrideId", "Id");

                            b1.ToTable("AvailabilityOverrideRanges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AvailabilityOverrideId");
                        });

                    b.Navigation("Ranges");
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingPage", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("BookingTracker.Domain.Entities.BookingFormField", "FormFields", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BookingPageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("int");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<byte>("Type")
                                .HasColumnType("tinyint");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingPageId", "DisplayOrder");

                            b1.ToTable("BookingFormFields", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookingPageId");
                        });

                    b.OwnsMany("BookingTracker.Domain.Entities.BookingQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BookingPageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("int");

                            b1.Property<string>("Prompt")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingPageId", "DisplayOrder");

                            b1.ToTable("BookingQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookingPageId");
                        });

                    b.Navigation("FormFields");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingReminder", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.BookingPage", null)
                        .WithMany()
                        .HasForeignKey("BookingPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingTracker.Domain.Entities.BookingSession", null)
                        .WithMany()
                        .HasForeignKey("BookingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSession", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.BookingPage", null)
                        .WithMany()
                        .HasForeignKey("BookingPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BookingTracker.Domain.ValueObjects.ClientContext", "LastContext", b1 =>
                        {
                            b1.Property<Guid>("BookingSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IpAddress")
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)")
                                .HasColumnName("LastClientIp");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("LastUserAgent");

                            b1.HasKey("BookingSessionId");

                            b1.ToTable("BookingSessions");

                            b1.WithOwner()
                                .HasForeignKey("BookingSessionId");
                        });

                    b.OwnsMany("BookingTracker.Domain.Entities.BookingSessionAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BookingFormFieldId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BookingSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingSessionId", "BookingFormFieldId")
                                .IsUnique();

                            b1.ToTable("BookingSessionAnswers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BookingSessionId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("LastContext")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSessionEvent", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.BookingPage", null)
                        .WithMany()
                        .HasForeignKey("BookingPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingTracker.Domain.Entities.BookingSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BookingTracker.Domain.ValueObjects.ClientContext", "Context", b1 =>
                        {
                            b1.Property<long>("BookingSessionEventId")
                                .HasColumnType("bigint");

                            b1.Property<string>("IpAddress")
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)")
                                .HasColumnName("ClientIp");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("UserAgent");

                            b1.HasKey("BookingSessionEventId");

                            b1.ToTable("BookingSessionEvents");

                            b1.WithOwner()
                                .HasForeignKey("BookingSessionEventId");
                        });

                    b.Navigation("Context")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.CalendarConnection", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.CalendarSyncedEvent", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.BookingSession", null)
                        .WithMany()
                        .HasForeignKey("BookingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingTracker.Domain.Entities.CalendarConnection", null)
                        .WithMany()
                        .HasForeignKey("CalendarConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.EmailNotification", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.BookingSession", null)
                        .WithMany()
                        .HasForeignKey("BookingSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.NotificationSettings", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingDay", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.WorkingSchedule", null)
                        .WithMany()
                        .HasForeignKey("WorkingScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("BookingTracker.Domain.ValueObjects.TimeRange", "Intervals", b1 =>
                        {
                            b1.Property<Guid>("WorkingDayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time")
                                .HasColumnName("EndTime");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time")
                                .HasColumnName("StartTime");

                            b1.HasKey("WorkingDayId", "Id");

                            b1.ToTable("WorkingDayIntervals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkingDayId");
                        });

                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingSchedule", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
