// <auto-generated />
using System;
using BookingTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingTrackerDbContext))]
    [Migration("20260730230331_AddBookingPageDescription")]
    partial class AddBookingPageDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingTracker.Domain.Entities.AvailabilityException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId", "Date");

                    b.ToTable("AvailabilityExceptions", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BufferAfterMinutes")
                        .HasColumnType("int");

                    b.Property<int>("BufferBeforeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BookingPages", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AbandonedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BookingPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastClientSequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("SelectedDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("SelectedTime")
                        .HasColumnType("time");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingPageId", "Status");

                    b.HasIndex("Status", "LastActivityAt");

                    b.ToTable("BookingSessions", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSessionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BookingPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClientSequenceNumber")
                        .HasColumnType("int");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint");

                    b.Property<string>("FieldName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingPageId", "Timestamp");

                    b.HasIndex("SessionId", "ClientSequenceNumber");

                    b.ToTable("BookingSessionEvents", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizers", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("OrganizerId", "ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("WorkingScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkingScheduleId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkingDays", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId")
                        .IsUnique();

                    b.ToTable("WorkingSchedules", (string)null);
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.AvailabilityException", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingPage", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSession", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.BookingPage", null)
                        .WithMany()
                        .HasForeignKey("BookingPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BookingTracker.Domain.ValueObjects.ClientContext", "LastContext", b1 =>
                        {
                            b1.Property<Guid>("BookingSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IpAddress")
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)")
                                .HasColumnName("LastClientIp");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("LastUserAgent");

                            b1.HasKey("BookingSessionId");

                            b1.ToTable("BookingSessions");

                            b1.WithOwner()
                                .HasForeignKey("BookingSessionId");
                        });

                    b.Navigation("LastContext")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.BookingSessionEvent", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.BookingPage", null)
                        .WithMany()
                        .HasForeignKey("BookingPageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingTracker.Domain.Entities.BookingSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BookingTracker.Domain.ValueObjects.ClientContext", "Context", b1 =>
                        {
                            b1.Property<long>("BookingSessionEventId")
                                .HasColumnType("bigint");

                            b1.Property<string>("IpAddress")
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)")
                                .HasColumnName("ClientIp");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("UserAgent");

                            b1.HasKey("BookingSessionEventId");

                            b1.ToTable("BookingSessionEvents");

                            b1.WithOwner()
                                .HasForeignKey("BookingSessionEventId");
                        });

                    b.Navigation("Context")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingDay", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.WorkingSchedule", null)
                        .WithMany()
                        .HasForeignKey("WorkingScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("BookingTracker.Domain.ValueObjects.TimeRange", "Intervals", b1 =>
                        {
                            b1.Property<Guid>("WorkingDayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time")
                                .HasColumnName("EndTime");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time")
                                .HasColumnName("StartTime");

                            b1.HasKey("WorkingDayId", "Id");

                            b1.ToTable("WorkingDayIntervals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkingDayId");
                        });

                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("BookingTracker.Domain.Entities.WorkingSchedule", b =>
                {
                    b.HasOne("BookingTracker.Domain.Entities.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
